micronaut:
  application:
    name: demoMicronautGraphql

graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    version: 0.13.2
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
    page-title: GraphiQL

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:micronautadm}
    password: ${JDBC_PASSWORD:"123456789"}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    schema-generate: CREATE_DROP
    dialect: H2