package demo.graphql.enuns;

public enum SubcategoriaInvestimento {
    CERTIFICADO_DEPOSITO_BANCARIO,
    CERTIFICADO_RECEBIVEIS_AGRONEGOCIO,
    CERTIFICADO_RECEBIVEIS_IMOBILIARIOS,
    DEBENTURES,
    DEPOSITO_PRAZO_COM_GARANTIA,
    FUNDO_INVESTIMENTO_DIREITOS_CREDITORIOS,
    LETRA_CAMBIO,
    LETRA_CREDITO_AGRONEGOCIO,
    LETRA_CREDITO_IMOBILIARIO,
    LETRA_FINANCEIRA,
    TESOURO_DIRETO,
    TITULOS_PUBLICOS_FEDERAIS
}
